// Public service information. Project scope remains subject to Zach's review.
import { websiteAnswer } from './search.mjs';
import { websiteKnowledge } from './knowledge.mjs';
export function answerQuestion(message) {
  const q = String(message || '').slice(0, 1000).toLowerCase();
  const result = (reply, service = '', url = ({'Driveway':'/grading','Grading / House Pad':'/grading','Land Clearing':'/land-clearing','French Drain':'/french-drains','Drainage Correction':'/drainage-correction','Erosion Control':'/civil-government','Other':'/civil-government'}[service] || '')) => ({ reply, service, links: url ? [{label:'Read more on our website',url}] : [] });
  if (/what.*(services|offer)|all.*services|\beverything\b|what (can|do) (you|y.all) do/.test(q) && !/price|cost|schedule|permit/.test(q)) return {reply:'Landco’s website lists land and brush clearing, forestry mulching, fence line and lot clearing, rough and finish grading, yard leveling, house and shed pad preparation, gravel driveway and access preparation, French drains, surface drainage, downspout tie-ins, drainage correction, erosion-control support, and civil or contractor site preparation. Ask about any of these, or send your scope for Zach’s review.',service:'',links:[{label:'Grading and site preparation',url:'/grading'},{label:'Clearing and mulching',url:'/land-clearing'},{label:'Drainage',url:'/french-drains'},{label:'Civil and contractor support',url:'/civil-government'}]};
  if (/concrete|asphalt|paving/.test(q)) return result('Landco prepares sites and installs or refreshes gravel drives. We do not pour concrete or asphalt. Tell us whether you need grading, a pad, or gravel work.', 'Driveway');
  if (/\b(price|cost|budget|rates?|discount)\b|how much/.test(q)) return result('Zach reviews each project before providing a price. Size, access, materials, water flow and site conditions affect the scope. Use Request a Quote to send your location, project details and photos directly to Landco.');
  if (/schedule|available|availability|tomorrow|today|appointment|book|start|urgent|emergency/.test(q)) return result('Call Landco directly at 912-254-1918 for timing or urgent requests. This assistant cannot reserve a date or confirm availability. For immediate danger, contact emergency services.');
  if (/guarantee|warranty|permit|engineer|licensed|insurance|insured|utility|legal/.test(q)) return result('Zach must review project requirements, site conditions, utility locations and any needed professional or jurisdictional approvals. This assistant cannot confirm permits, coverage or guarantees. Call 912-254-1918 or request a project review.');
  const massGrading = /mass\s+grad|bulk\s+(grad|earth|excav)|earth\s*mov|large[-\s]+scale\s+grad/.test(q);
  const landscaping = /landscap|lawn|mow|planting|sod|garden|hardscap/.test(q);
  const gradingReply = 'Yes—Landco handles rough and finish grading and site preparation. For mass grading or bulk earthmoving, Zach reviews the acreage, cut-and-fill requirements, access and plans before confirming the scope. What size project and city are you considering?';
  const landscapeReply = 'For landscaping projects, Landco handles ground preparation, grading, drainage, clearing and erosion control. Planting, lawn mowing, ongoing maintenance and decorative landscaping need confirmation from Zach. What kind of landscaping do you need?';
  if (massGrading && landscaping) return result(gradingReply + '\n\n' + landscapeReply, 'Grading / House Pad', '/grading');
  if (massGrading) return result(gradingReply, 'Grading / House Pad', '/grading');
  if (landscaping) return result(landscapeReply, '', '/grading');
  const cities = websiteKnowledge.filter(x => x.url === '/service-areas' && /, GA$/.test(x.title));
  const city = cities.find(x => q.includes(x.title.replace(', GA','').toLowerCase()));
  if (city) return result(city.title + ': ' + city.text + '\nZach confirms availability and project fit after review.', '', '/service-areas');
  if (/service area|where|serve|county|counties|north georgia/.test(q)) return result('Landco’s website lists ' + cities.map(x => x.title.replace(', GA','')).join(', ') + '. County coverage includes Athens-Clarke, Oconee, Gwinnett, Barrow, Walton, Jackson and Rockdale. Availability depends on scope, access and mobilization.', '', '/service-areas');
  const found = websiteAnswer(message);
  if (found) return found;
  if (/french|drain|water|flood|downspout|catch basin|creek|washout/.test(q)) return result('Landco handles French drains, surface drains, downspout tie-ins, dry creek beds and drainage correction. Standing surface water and subsurface water may need different approaches; Zach reviews elevations, water paths and the outlet before recommending a solution. What is happening on your property?', /french/.test(q) ? 'French Drain' : 'Drainage Correction');
  if (/driveway|gravel|crusher|rock/.test(q)) return result('Landco grades and refreshes gravel driveways, corrects runoff and prepares gravel access. Describe the approximate size, existing surface and any washouts in your quote request.', 'Driveway');
  if (/clear|mulch|brush|forestry|fence line|overgrowth/.test(q)) return result('Landco provides land clearing, forestry mulching, brush removal and fence line clearing. Include the approximate area, vegetation, access and desired finish in your quote request.', 'Land Clearing');
  if (/erosion|silt|seed|straw|matting/.test(q)) return result('Landco provides erosion-control work, including silt fence, seeding and protective matting. Zach reviews the slope, runoff, disturbed area and project requirements.', 'Erosion Control');
  if (/grad|pad|shed|level|slope|site prep/.test(q)) return result('Landco handles rough and finish grading, shed and house pads, slope correction and site preparation. Include dimensions, access, existing slope and intended use in your quote request.', 'Grading / House Pad');
  if (/civil|government|detention|trench|storm|road/.test(q)) return result('Landco supports civil site preparation, grading, drainage correction, access preparation, clearing, erosion-control support and defined contractor scopes. Send the scope, location and available plans for Zach’s review.', 'Other');
  if (/contact|call|phone|human|zach|person|email|text/.test(q)) return result('Contact Zach at Landco directly: call or text 912-254-1918, or email landcodevelopment2@gmail.com. You can also send details and photos through Request a Quote.');
  if (/photo|picture/.test(q)) return result('Add up to three project photos in the quote form. Keep the combined upload under 8 MB. Upload only photos you have authority to share, and leave out sensitive information.');
  return result('I couldn’t find a clear answer to that in Landco’s website information. Try naming the service or asking about clearing, grading, drainage, gravel access, civil sitework, service areas, project photos or quote requests. Zach can confirm anything not listed: call 912-254-1918.');
}
