// Shared, approved public information. Also embedded in the n8n Code node.
export function answerQuestion(message) {
  const q = String(message || '').slice(0, 1000).toLowerCase();
  const result = (reply, service = '') => ({ reply, service });
  if (/concrete|asphalt|paving/.test(q)) return result('Landco prepares sites and installs or refreshes gravel drives. We do not pour concrete or asphalt. Tell us whether you need grading, a pad, or gravel work.', 'Driveway');
  if (/price|cost|quote|estimate|budget|how much|rate|discount/.test(q)) return result('Zach reviews each project before providing a price. Size, access, materials, water flow and site conditions affect the scope. Use Request a Quote to send your location, project details and photos directly to Landco.');
  if (/schedule|available|availability|tomorrow|today|appointment|book|start|urgent|emergency/.test(q)) return result('Call Landco directly at 912-254-1918 for timing or urgent requests. This assistant cannot reserve a date or confirm availability. For immediate danger, contact emergency services.');
  if (/guarantee|warranty|permit|engineer|licensed|insurance|insured|utility|legal/.test(q)) return result('Zach must review project requirements, site conditions, utility locations and any needed professional or jurisdictional approvals. This assistant cannot confirm permits, coverage or guarantees. Call 912-254-1918 or request a project review.');
  if (/service area|where|serve|athens|conyers|gwinnett|lawrenceville|dacula|auburn|winder|snellville|loganville|monroe|bogart|jefferson|braselton|hoschton|north georgia/.test(q)) return result('Landco serves Athens, Conyers, Gwinnett County and surrounding North Georgia communities, including Lawrenceville, Dacula, Auburn, Winder, Snellville, Loganville, Monroe, Bogart, Jefferson, Braselton and Hoschton. Zach confirms project fit and mobilization after review.');
  if (/french|drain|water|flood|downspout|catch basin|creek|washout/.test(q)) return result('Landco handles French drains, surface drains, downspout tie-ins, dry creek beds and drainage correction. Standing surface water and subsurface water may need different approaches; Zach reviews elevations, water paths and the outlet before recommending a solution. What is happening on your property?', /french/.test(q) ? 'French Drain' : 'Drainage Correction');
  if (/driveway|gravel|crusher|rock/.test(q)) return result('Landco grades and refreshes gravel driveways, corrects runoff and prepares gravel access. Describe the approximate size, existing surface and any washouts in your quote request.', 'Driveway');
  if (/clear|mulch|brush|forestry|fence line|overgrowth/.test(q)) return result('Landco provides land clearing, forestry mulching, brush removal and fence line clearing. Include the approximate area, vegetation, access and desired finish in your quote request.', 'Land Clearing');
  if (/erosion|silt|seed|straw|matting/.test(q)) return result('Landco provides erosion-control work, including silt fence, seeding and protective matting. Zach reviews the slope, runoff, disturbed area and project requirements.', 'Erosion Control');
  if (/grad|pad|shed|level|slope|site prep/.test(q)) return result('Landco handles rough and finish grading, shed and house pads, slope correction and site preparation. Include dimensions, access, existing slope and intended use in your quote request.', 'Grading / House Pad');
  if (/civil|government|detention|trench|storm|road/.test(q)) return result('Landco accepts civil and sitework inquiries, including utility trenching, storm drains, gravel roads and detention pond excavation. Send the scope, location and available plans for review.', 'Other');
  if (/contact|call|phone|human|zach|person|email|text/.test(q)) return result('Contact Zach at Landco directly: call or text 912-254-1918, or email landcodevelopment2@gmail.com. You can also send details and photos through Request a Quote.');
  if (/photo|picture/.test(q)) return result('Add up to three project photos in the quote form. Keep the combined upload under 8 MB. Upload only photos you have authority to share, and leave out sensitive information.');
  return result('I can help with drainage, grading and pads, gravel driveways, land clearing, erosion control and service areas. For a project-specific answer, use Request a Quote or call Zach directly at 912-254-1918.');
}
